### ISSUE TITLE
GitHub Actions Hanging

### ISSUE THREAD

**Issue by eseay** [mParticle/mparticle-apple-sdk#191]
After updating our mParticle version to v8.13.0, we noticed that GitHub Actions CI jobs are hanging indefinitely - in particular, our `xcodebuild test` invocations. They get to the end of package resolution and just sit there.

I noticed that in [this commit](https://github.com/mParticle/mparticle-apple-sdk/commit/e482df0c9496d47e73276655afd72a4f483b2d66), you updated mParticle to leverage binary targets instead of source targets, and my hypothesis is that this is related to the issue.

By pinning explicitly to v8.12.0 (pre-binary targets), the issue went away.

Last week, when we integrated Lottie into our app, we noticed the same exact behavior. This is discussed in [this issue](https://github.com/airbnb/lottie-ios/issues/2051) on the Lottie repository.

There is one striking similarity. Lottie suggests depending on [lottie-spm](https://github.com/airbnb/lottie-spm/blob/main/Package.swift) to get the benefits of binary targets, so we did that. After integrating it, we saw our actions hanging. Per the suggestion of their engineers, we tried to build from source instead via [lottie-ios](https://github.com/airbnb/lottie-ios/blob/master/Package.swift), and we noticed that the problem went away.

So the request isn't necessarily to solve this problem at its root for my team, but perhaps would it be possible to offer the option of building from source in addition to binary targets until we can determine the root cause? We're pretty aggressive abound updating our mParticle version to always be on the latest, so I'd really prefer not to pin to an outdated version for a long time.

**Comment by einsteinx2** [comment]
Thank you for the feedback, this is very valuable to know. Unfortunately, SPM currently does not support source targets for mixed Objective-C and Swift targets. That's why we moved to binary targets. Cocoapods does support building from source though, so that's an option, though that's obviously a bigger change since it forces you into their xcworkspace format...

Could you provide a minimum test project that reproduces the CI issue? I'd like to look into it on our end. Maybe a stripped down version of your project and workflow that you can share?

**Comment by einsteinx2** [comment]
Also fwiw, some of our popular partner SDKs used with our kits, such as Braze, also use binary targets, though our Braze kit itself is currently all Objective-C and so is a source target, but does have Braze's binary target as a dependency in SPM. We hadn't heard of any issues from customers regarding CI issues using our Braze kit, so I wonder what's different about this case that's causing the issue.

Also does `xcodebuild test` work on your local machine? That is to say, is this a CI only issue?

**Comment by eseay** [comment]
@einsteinx2 I'll try to whip something up to reproduce it. Our project is so large that the only way I'm going to be able to provide anything will be by trying to create a fake app project from scratch.

To the second question - yes - it works on my local machine, which is the most puzzling part.

**Comment by einsteinx2** [comment]
@timsearle Thanks this is a great data point!

**Comment by einsteinx2** [comment]
@eseay and @timsearle can you confirm what macOS and Xcode version you're both using on your CI runners, and @timsearle which macOS and Xcode version you used to reproduce that issue on your machine?

For example, on Ventura and Xcode 14.3, I add the package to a new project and it never prompts me. I confirmed I don't even have my Github credentials in my keychain at all, so I didn't accidentally hit "always allow" in the past or anything like that.

The strange thing is, if you try to manually download the link from the package.swift file, it downloads without any authentication (since it's just linking to the Github release page and the repo is public). Here's the link for reference: https://github.com/mParticle/mparticle-apple-sdk/releases/download/v8.13.0/mParticle_Apple_SDK.xcframework.zip

**Comment by timsearle** [comment]
https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/MACOS/M1/osx-xcode-14.3.x-ventura.log

This is the system report for our current CI runner where we experience this issue.

**Comment by einsteinx2** [comment]
@timsearle Thanks I'll take a look! 

Can you do me one more favor. I'm trying to rule out whether it's prompting the password when just accessing the repo or when actually downloading the artifacts, so I uploaded the same 8.13.0 artifacts to a public S3 bucket and updated package.swift in a fork on my account to point to them. I then tagged and created an 8.13.0 release on that repo (didn't want to mess with tags/main on the mParticle repo).

Can you please try creating a fresh project and adding the SPM package from this repo instead of the main one and see if it prompts for a password like before: https://github.com/einsteinx2/mparticle-apple-sdk

**Comment by eseay** [comment]
@einsteinx2 following up from your question a few days ago - we're using Xcode 14.3 and macOS 13.

**Comment by timsearle** [comment]
@einsteinx2 I performed your test on the fork, and was *not* prompted for a password. I am able to reliably reproduce the issue on my machine with the official repo if I delete the cached checkout for the SDK from `~/Library/Caches/org.swift.swiftpm`.

For completeness, I'm running on Xcode 14.3 (14E222b) with the respective command line tools, and on Venture 13.3.1 (a)

**Comment by einsteinx2** [comment]
So quick follow up on this. As it happens, our CI issue was unrelated and resolved itself without intervention. I am also totally unable to reproduce this password prompt issue on my machine for some reason, but it's clear that the issue is likely within Xcode and presumably it's either confusing a regular github URL with a password protected HTTPS git repo on github (no idea how that could happen but here we are) or github is for some reason password protecting that link when Xcode connects to it...but only for some people...and the link is public if you access it from a browser...

Yeah nothing really makes sense, but since S3 is working for you, it's clear that it has something to do with linking directly to a github release artifact. I'm going to work with my team to get the artifacts uploaded to S3 and referenced from there, which should resolve the issue.

I'll reply here when the change as been made. It will coincide with a point release, so it should be v8.14.0 and should not require any changes to projects using mParticle via SPM other than just pulling the latest version (which CI already presumably does).

**Comment by eseay** [comment]
Hey @einsteinx2 @timsearle - I wanted to provide an update on this. In working with GitHub support, we were able to determine that the the issue can be resolved by adding a `.netrc` file to the filesystem that allows the CLI (xcodebuild in particular) to authenticate with GitHub.com and api.github.com.

It seems someone else in a pretty old issue ran into this too: https://github.com/actions/runner-images/issues/6233#issuecomment-1247983767

I have added the following step to my workflows, and all is working well! (note that the actual secret key will likely differ)

```
- name: Add .netrc
  run: |
    echo -e "machine github.com\n  login oauth2\n  password ${{ secrets.GITHUB_TOKEN }}\n" > ~/.netrc
    echo -e "machine api.github.com\n  login oauth2\n  password ${{ secrets.GITHUB_TOKEN }}\n" >> ~/.netrc
  shell: sh
```

Thanks again @einsteinx2 for taking the time to look into this. Perhaps something related to this solution could be added to the docs in case anyone else runs up against it.

**Comment by einsteinx2** [comment]
@eseay Thanks for the information! Ultimately I ended up getting a PR in today to switch to using S3 for SPM to sidestep the issue completely. 

Glad to hear there's a workaround when using Github releases for the artifacts, but honestly no one should need to authenticate in the first place so hopefully the S3 solution will make things easier for everyone and you won't need the netrc workaround anymore either. 

As of our next release, the URLs for SPM will now point to a public S3 bucket, so there should be no more authentication prompts at all.
