### ISSUE TITLE
mParticle_Apple_SDK/mParticle_Apple_SDK-Swift.h' file not found

### ISSUE THREAD

**Issue by ashuiOSDeveloper** [mParticle/mparticle-apple-sdk#198]
I have followed the steps as per the comments mentioned on previous issue. I
https://github.com/mParticle/mparticle-apple-sdk/issues/195

But, I am still getting the same error.

**Comment by ashuiOSDeveloper** [comment]
<img width="709" alt="File not available on git" src="https://github.com/mParticle/mparticle-apple-sdk/assets/68823566/56aafa9f-2917-4f4a-a648-f192bb23305a">
<img width="1265" alt="FIle not found Xcode" src="https://github.com/mParticle/mparticle-apple-sdk/assets/68823566/da81c10f-6ee6-44ae-9a17-438a45069ef5">

**Comment by einsteinx2** [comment]
Hi sorry I looked at the other ticket and saw that I made a typo, it should be `use_frameworks!` with the exclamation point at the end. And that should be added at the top of the `target` section for each target in your Podfile.

That mParticle_Apple_SDK-Swift.h file does not exist in the repository because it is auto-generated by Xcode during the build process. 

Normally when using Cocoapods, the reason it's not built is due to missing the `use_frameworks!` directive, so if you've added that and it's still not working, I need to see the whole file to see if possibly it was added in the wrong place or something.

Can you please confirm that when adding `use_frameworks!` to your target you still see the issue? You may also need to delete the `Pods` directory and `Podfile.lock` file before running `pod update` again after updating your Podfile.

If you still have problems, please post the whole Podfile. I'll leave this issue open until you confirm it's working.

**Comment by ashuiOSDeveloper** [comment]
I have tried deleting the directory and `podfile.lock`.
I have also added the `use_frameworks`! before every `target`.
I ran the `pod update` command but the result is same.
I will not be able to post the whole `podfile` due to privacy reasons.
But, I am adding few lines in here, hope that may help

```
platform :ios, '14.0'
deployment_target = '14.0'
inhibit_all_warnings!
use_frameworks!

project 'XXXXXX', 'XCTest' => :'debug'

target 'XXXXXX' do
```

**Comment by einsteinx2** [comment]
Hmm this is really strange. The fix I proposed has resolved the issue for all other customers that have reported this issue. It seems like something else must be going on here... 

Can you confirm which version of macOS and Xcode you're using?

**Comment by ashuiOSDeveloper** [comment]
Xcode version -Version 14.3 (14E222b)
Mac OS version - 13.3.1 (a) (22E772610a)

My Macbook Air has Apple M1 chip, could that be the reason for any discrepancy?

**Comment by ashuiOSDeveloper** [comment]
<img width="644" alt="Screenshot 2023-06-22 at 2 37 48 PM" src="https://github.com/mParticle/mparticle-apple-sdk/assets/68823566/569e9960-cd0e-4aab-a97e-def986c48127">

**Comment by ashuiOSDeveloper** [comment]
Hello,
Any update regarding this ?

**Comment by einsteinx2** [comment]
Hi sorry for the delayed reply. We fully support M1/M2 Macs, so that should not be a problem. I'm honestly out of ideas, as this works fine for all of us here and all other customers using Cocoapods that I'm aware of...

What happens if you remove the line from your podfile, download the xcframework directly from our releases page, and drop it directly into your project?

Otherwise, for continued one on one troubleshooting, please open a support ticket here: https://support.mparticle.com
