### ISSUE TITLE
mParticle conflicts with uni_links on deep linking handling

### ISSUE THREAD

**Issue by theideasaler** [mParticle/mparticle-apple-sdk#203]
The flutter project I am working for is using [uni_links](https://pub.dev/packages/uni_links) to handle the deep linking link changes.

However, when I integrated mParticle sdk into my project, I found the linkStream from `uni_links` stops working

```dart
uriLinkStream.listen((Uri? uri) {
      // This method no longer works after integrating with uni_links
    };
```

I assume there are some conflicts in mParticle Flutter SDK in regard the channel link stream.

I want to keep the deep linking handling as it was. 

So could you please suggest a way to disable the mParticle on the deep linking handling?

**Comment by einsteinx2** [comment]
It's hard to know what the problem is for sure, but I have a hunch it may be related to our proxying of the UIApplicationDelegate. I see here in that library it expects to inject(?) some code into the delegate methods (https://github.com/avioli/uni_links/blob/master/uni_links/ios/Classes/UniLinksPlugin.m) and that may not be happening...

My first suggestion would be to disable app delegate proxying. You'll need to do some manual setup in the UIApplicationDelegate in your app, so please take a look at the documentation here: https://docs.mparticle.com/developers/sdk/ios/configuration/#uiapplication-delegate-proxy

Please give that a shot and see if deep linking works. You can do a quick smoke test of this theory by just disabling the proxying (using the `proxyAppDelegate ` property of the `MParticleOptions` object) and hold off on the rest until you confirm that deep links start working.

**Comment by theideasaler** [comment]
Hi @einsteinx2 , thank you for the suggestion, it seems to be the solution - after the setting the `proxyAppDelegate` to `false`, the uni_links callback is now working again.
