### ISSUE TITLE
When to call checkForDeferredDeepLinkWithCompletionHandler to register a deep link handler?

### ISSUE THREAD

**Issue by twobitlabs** [mParticle/mparticle-apple-sdk#27]
With Branch it's easy to register a deep link handler when you init the session in didFinishLaunchingWithOptions. Then that deep link handler is called whenever a deep link is processed by branch.

With mParticle since the Branch kit is initialized asynchronously it's not clear when to make the call. If we call checkForDeferredDeepLinkWithCompletionHandler in didFinishLaunchingWithOptions it's too early since the Branch kit hasn't been initialized yet so the handler is just discarded by the mParticle SDK.

When is the correct time to call checkForDeferredDeepLinkWithCompletionHandler to register a deep link handler?

**Comment by dcirne** [comment]
Hi @twobitlabs,

The mParticle SDK broadcasts a notification (`mParticleKitDidBecomeActiveNotification`) when a kit becomes available. Once you receive that notification it is safe to use a kit since it will be guaranteed to be initialized.

A great example on how to register to listen for the kit became available notification and how to use deep-linking with Branch can be found in this gist: https://gist.github.com/dcirne/ba7ba9f8d53a3d8820c5b043e289a22c

Let us know if you have any questions.

**Comment by twobitlabs** [comment]
Thanks, that helps!
