### ISSUE TITLE
Support -[UIApplicationDelegate application:didReceiveRemoteNotification:fetchCompletionHandler:]

### ISSUE THREAD

**Issue by saniul** [mParticle/mparticle-apple-sdk#30]
Looks like you supported some of the new UNUserNotification methods in https://github.com/mParticle/mparticle-apple-sdk/commit/4e2d46c7c0bb591e9b5d5d51bd8cc3f342ef43a7 - that's great!

Just a heads up, there's one more method that you probably want to support and pass-through to kits like AppBoy:

`- (void) application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler`

**Comment by dcirne** [comment]
Hi @saniul, thanks for the feedback!

We do already support the method you mentioned (https://github.com/mParticle/mparticle-apple-sdk/blob/master/mParticle-Apple-SDK/mParticle.h#L261). However in most cases you don't need to call it directly, because we proxy the app delegate and handle the forwarding for you.

**Comment by saniul** [comment]
Oof, my bad, for some reason I thought this was a new method just now 🙃 Sorry about that, closing.
