### ISSUE TITLE
Extension Support

### ISSUE THREAD

**Issue by dmiluski** [mParticle/mparticle-apple-sdk#39]
ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/dmiluski/Library/Developer/Xcode/DerivedData/<App>/Build/Products/Debug-iphonesimulator/mParticle_Apple_SDK.framework/mParticle_Apple_SDK

I am seeing a warning if I attempt to use mParticle SDK in an extension of an app.

Version: Release 6.13
Xcode 8.3.2 (8E2002)
Integration: Carthage Submodule

Could this SDK be made extension friendly? Or am I importing/including something incorrectly?

https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html

**Comment by samdozor** [comment]
hey @dmiluski the Core Apple SDK does not support extensions at this time. This is something we're actively prioritizing, though. Please reach out to your mParticle customer support / or hit us on Slack, and we can chat through your use cases. Thanks!

**Comment by dmiluski** [comment]
Thanks

**Comment by lehrblogger** [comment]
Thanks @samdozor – I know that you and I have chatted about this as well, but we would still be very interested in support for mParticle event logging in iOS extensions.

**Comment by dmiluski** [comment]
I wasn't familiar with the issue. Is it about backgroundTasks? Or something else?

**Comment by samdozor** [comment]
@dmiluski speaking specifically - there is no accessible UIApplication in an extension. Our SDK (and others that we wrap) require the UIApplication to determine foregrounds, background, etc. The whole notion of a "session" is very different in an extension paradigm.

Broadly speaking - we want to be certain of data integrity/consistency, and that actions are attributed to the correct user identity, both in our platform and in any downstream integrations. An extension is generally part of another app, not your core app, and therefore it may be desired to treat events in an extension as separate - but surely there are different schools of thought here.

**Comment by Nonnus** [comment]
> An extension is generally part of another app, not your core app
this is not correct at all, "my" app extensions are part of "my" app, not part of "another app", not "generally", not ever... app extensions are just alternative targets from a single app, at least from a developers perspective which is what matters for the purpose of mParticle sdk integration... 

my company is currently evaluating adoption of mParticle as you been very insistent trying to get our business and we are supposed to have some presentation session soon and this was exactly one of the topics i was going to ask about because we do require sending tracking event from our app extensions and will really not consider mParticle otherwise

needless to say this new info will now be debated among my team even before our upcoming session which i now fear might end up not even taking place due to this unfortunate lack of extensions event logging support

**Comment by samdozor** [comment]
hey @Nonnus sorry what I was trying to point out is - extensions are part of the user experience of a 3rd-party  "host" app (rather than your "containing" app), Xcode setup notwithstanding, and the metrics of the extension could be treated differently depending on how you view it. Our product and data science teams need to ensure that user identity, session management, and other metrics are accurately reflective of this.

We are targeting full extension support for Q4 and will keep you updated as we know the specific date for release. Until then there are a few simple workarounds you can do that would allow you to pipe data from an extension to your core app via a shared `NSUserDefaults` suite, for example.

**Comment by Nonnus** [comment]
thanks a lot for your reply @samdozor

are there any news regarding full extension support from your side?

also, can you point to some resources regarding using shared `NSUserDefaults` suite for tracking events?
i assume the concept is basically storing any extension tracking events in shared user defaults and then access them on "real app" start and log them,
however, i am especially intrigued about event timestamps and how to preserve them

**Comment by samdozor** [comment]
Hi @Nonnus and @dmiluski - hanks for your patience on this! 

I wanted to let you know that we've released extension support in the new Apple SDK, version 7.1.0. Note that version 7 of the SDK also requires that your org is provisioned for mParticle IDSync.

Depending on how you'd like to treat extension data, there are a few configurable APIs that we've surfaced, such as allowing you to share persistence and identities between your primary app and the extension, turning-off session management, etc. 

Please check out the docs here: https://docs.mparticle.com/developers/sdk/ios/app-extensions
