### ISSUE TITLE
Identity Request nil customer and email IDs causes a crash

### ISSUE THREAD

**Issue by palmaya** [mParticle/mparticle-apple-sdk#61]
https://github.com/mParticle/mparticle-apple-sdk/blob/d82a3b333576a5907c5f1703718f06686386a107/mParticle-Apple-SDK/Identity/MPIdentityApiRequest.h#L18

When updating to the latest SDK (7.1.1), the previous call to setUserIdentity with customerID = nil and emailID = nil was converted to an identity request. It appears that setting request.email = nil or request.customerId = nil before attempting to login will result in a crash, even though the API accepts nil.

**Comment by samdozor** [comment]
Hi @palmaya we're taking a look at this as this certainly shouldn't be crashing.

That said - I'd like to confirm the use case for setting those to nil. Are you looking to remove user identities from an existing user? In the new Identity API, you should perform a `modify` request to do that. Otherwise, if you're performing a `login` or a `logout`, you just shouldn't populate customerid or email in the identity request at all, rather than setting them to nil.

**Comment by samdozor** [comment]
@palmaya please let me know if you're still able to reproduce this. Thanks!
