### ISSUE TITLE
Missing Migration Guide for v7 release

### ISSUE THREAD

**Issue by dmiluski** [mParticle/mparticle-apple-sdk#62]
Problem:
1. The latest v6 releases broke backwards compatibility (semVersion) specifies patch changes should not break backwards compatibilities for the major version.

2. In addition to not having a migration guide for v7, The latest v7 release fails to provide deprecation/rename mappings for new interface to help dev migrate without even reading a doc.

Request:
Can you provide a mapping/migration from v6 to v7?
I was very confused at how to report user change? Given user one logs in after mParticle is started? Vs logout, then another logs in?

Are we supposed to keep a reference of options and update that object with a new identity request?

What is the difference between MParticleUser vs MPIdentityApiRequest?

**Comment by samdozor** [comment]
@dmiluski which change to v6 is breaking backwards compatibility for you?

**Comment by dmiluski** [comment]
Hi @samdozor, I was recently attempting to update from 6.15.17 -> 6.16.1, and was surprised to see the start(x,x,x) function was a breaking change. Attempting to migrate to v7 now, and reading through your linked guides. Thanks for the reference.

**Comment by dmiluski** [comment]
Hi @samdozor as a followup reading about identity, I noticed modify doesn't create a new user:
http://docs.mparticle.com/developers/sdk/ios/identity#creating-a-request

What happens if the initial login fails? Is there recommended error handling/retry? Or any further documents for those use cases? Current migration has us calling modify on account updates (for changes such as email/phone etc..) But I got to thinking about what if the initial *.Identity.login fails? What would happen to future modify calls?

**Comment by samdozor** [comment]
Hi @dmiluski, hmm so far as I know there have been no breaking changes to `start` in 6.x. There are only breaking changes to `start` in 7.x, with the introduction of the `MParticleOptions` object.

If you call `modify`, and there is no user to modify, you will receive an error noting that you've made a bad request. You will have a user as long as the SDK has *ever* successfully called `identify`, `login`, or `logout` in the past, across app restarts.

To dig a little deeper - the SDK will automatically call `identify` on initialization (rather than `login`), and you can customize the identities passed to that initial call by populating the `identifyRequest` property of the MParticleOptions object.

You can listen for both success and failure of this initial request by setting the `onIdentifyComplete` block property of the `MParticleOptions` object:

```
MParticleOptions *mParticleOptions = [MParticleOptions optionsWithKey:@"foo-key"
                                                                   secret:@"bar-secret"];
mParticleOptions.onIdentifyComplete = ^(MPIdentityApiResult * _Nullable apiResult, NSError * _Nullable error) {
        NSLog(@"Identify complete. userId = %@ error = %@", apiResult.user.userId, error);
        
        if (error.userInfo[mParticleIdentityErrorKey]) {
            MPIdentityHTTPErrorResponse *errorResponse = error.userInfo[mParticleIdentityErrorKey];
            NSLog(@"Error response. httpCode = %@ code = %@ message = %@", @(errorResponse.httpCode), errorResponse.code, errorResponse.message);
        }
};
[[MParticle sharedInstance] startWithOptions:mParticleOptions];
```

If there is an error, you will be able to parse it out of the `NSError` object using the `mParticleIdentityErrorKey` value that we publish in MPEnums.h as shown above. We also publish common error codes that you may receive depending on the nature of the error, and suggest you retry the request if necessary. 

You can see the common errors published here: https://github.com/mParticle/mparticle-apple-sdk/blob/master/mParticle-Apple-SDK/MPEnums.h#L259

And here's more information on error handling in our docs: http://docs.mparticle.com/developers/sdk/ios/identity#error-handling

I am closing this issue for now but please feel free to follow up via Slack or email.
